apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/mlops-gitops.git
    path: infrastructure
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
