apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    chart: jupyterhub
    targetRevision: 2.3.0
    helm:
      valueFiles:
        - helm-values/jupyterlab-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: python-ide
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
