apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 15.0.0
  - repoURL: https://github.com/Marius2311/wdski23a-mlops-gitops.git
    targetRevision: main
    ref: values

  source:
    helm:
      valueFiles:
        - $values/helm-values/minio-values.yaml
      timeout: 300

  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
