apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://github.com/Pharia/helm-charts
    chart: mlflow
    targetRevision: main
    helm:
      valueFiles:
        - $values/helm-values/mlflow-values.yaml
      timeout: 300
  - repoURL: https://github.com/Marius2311/wdski23a-mlops-gitops.git
    targetRevision: main
    ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true