apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: mlops
spec:
  project: default

  source:
    repoURL: https://github.com/Marius2311/wdski23a-mlops-gitops.git
    targetRevision: main
    chart: mlflow
    helm:
      valueFiles:
        - helm-values/mlflow-values.yaml
    path: .  # path is ignored for Helm charts
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
