apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.2.0
    helm:
      valueFiles:
        - $values/helm-values/postgres-values.yaml
      timeout: 300
  - repoURL: https://github.com/Marius2311/wdski23a-mlops-gitops.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
