apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-secretstore
  namespace: data-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-secretstore-role
  namespace: data-storage
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-secretstore-rb
  namespace: data-storage
subjects:
- kind: ServiceAccount
  name: eso-secretstore
  namespace: data-storage
roleRef:
  kind: Role
  name: eso-secretstore-role
  apiGroup: rbac.authorization.k8s.io
