apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: data-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: SecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: minio-root
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: minio-root
        property: root-password
