apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cluster-secret-store
  namespace: data-storage
spec:
  provider: 
    kubernetes:
      remoteNamespace: data-storage
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tIE1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAgWlc1MExXTmhRREUzTmpJek5qWTNOamt3SGhjTk1qVXhNVEExTVRneE9USTVXaGNOTXpVeE1UQXpNVGd4T1RJNSBXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTmpJek5qWTNOamt3V1RBVEJnY3Foa2pPIFBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTOVYxR0lUMmhKZ3ozc3o4emNXREdQMjVuOXJuekF6aGZnQ2s5b0lzL04gK0dvWlZGSDBCejFkakwraDB6dHZVUkU2RzRsN3M1R0R4SXc0akR4dDhucVVvMEl3UURBT0JnTlZIUThCQWY4RSBCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXRVd3VwMkp6dnBTSXcxdjZLbVhkIHpyNGZZVjh3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU9YNWkrTVJteG51YTNnQitVbWtCWnFOdDBSOGpRUnAgKzd0S2ZIdHc4RVF5QWlFQWlSUVR6b2c3MFNvcCs2SUNBbVhleEZIR0RNQi9RQ0hDSnlsbmNDU2pjdTA9IC0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=