apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: minio-extract-and-echo
  namespace: argo-workflows
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: event-envelope-json
        value: ""
  templates:
    - name: main
      steps:
        - - name: extract
            template: extract
            arguments:
              parameters:
                - name: event-envelope-json
                  value: "{{workflow.parameters.event-envelope-json}}"
        - - name: echo
            template: echo
            arguments:
              parameters:
                - name: bucket
                  value: "{{steps.extract.outputs.parameters.bucket}}"
                - name: key
                  value: "{{steps.extract.outputs.parameters.key}}"

    - name: extract
      inputs:
        parameters:
          - name: event-envelope-json
      outputs:
        parameters:
          - name: bucket
            valueFrom:
              path: /tmp/bucket.txt
          - name: key
            valueFrom:
              path: /tmp/key.txt
      container:
        image: alpine:3.20
        command: [sh, -lc]
        args:
          - |
            set -euo pipefail
            apk add --no-cache jq >/dev/null

            # 1) Envelope JSON exakt schreiben (ohne echo-quotes Probleme)
            printf '%s' '{{inputs.parameters.event-envelope-json}}' > /tmp/envelope.json

            # 2) Envelope validieren
            jq -e . >/dev/null < /tmp/envelope.json

            # 3) Base64 payload aus .data ziehen und decoden
            jq -r '.data' /tmp/envelope.json > /tmp/payload.b64
            base64 -d /tmp/payload.b64 > /tmp/event.json

            # 4) Event JSON validieren
            jq -e . >/dev/null < /tmp/event.json

            # 5) bucket/key extrahieren
            jq -r '.notification[0].s3.bucket.name' /tmp/event.json > /tmp/bucket.txt
            jq -r '.notification[0].s3.object.key' /tmp/event.json > /tmp/key.txt

    - name: echo
      inputs:
        parameters:
          - name: bucket
          - name: key
      container:
        image: alpine:3.20
        command: [sh, -lc]
        args:
          - |
            echo "bucket={{inputs.parameters.bucket}}"
            echo "key={{inputs.parameters.key}}"
