apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: minio-extract-and-echo
  namespace: argo-workflows
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: event-envelope-json
        value: ""
  templates:
    - name: main
      steps:
        - - name: extract
            template: extract
            arguments:
              parameters:
                - name: event-envelope-json
                  value: "{{workflow.parameters.event-envelope-json}}"
        - - name: echo
            template: echo
            arguments:
              parameters:
                - name: bucket
                  value: "{{steps.extract.outputs.parameters.bucket}}"
                - name: key
                  value: "{{steps.extract.outputs.parameters.key}}"

    - name: extract
      inputs:
        parameters:
          - name: event-envelope-json
      outputs:
        parameters:
          - name: bucket
            valueFrom:
              path: /tmp/bucket.txt
          - name: key
            valueFrom:
              path: /tmp/key.txt
      container:
        image: alpine:3.20
        command: [sh, -lc]
        args:
          - |
            set -euxo pipefail
            : > /tmp/bucket.txt
            : > /tmp/key.txt
            apk add --no-cache jq >/dev/null

            echo "[1] writing envelope"
            printf '%s' '{{inputs.parameters.event-envelope-json}}' > /tmp/envelope.json
            echo "[1] envelope bytes: $(wc -c </tmp/envelope.json)"
            echo "[1] envelope head:"
            head -c 200 /tmp/envelope.json || true
            echo

            echo "[2] validate envelope json"
            jq -e . >/dev/null < /tmp/envelope.json || { echo "ENVELOPE JSON INVALID"; exit 10; }

            echo "[3] extract .data (base64 payload) from envelope"
            jq -r '.data' /tmp/envelope.json > /tmp/payload.b64 || { echo "FAILED jq .data"; exit 11; }
            echo "[3] payload.b64 bytes: $(wc -c </tmp/payload.b64)"
            echo "[3] payload.b64 head:"
            head -c 80 /tmp/payload.b64 || true
            echo

            echo "[4] base64 decode payload -> event.json"
            base64 -d /tmp/payload.b64 > /tmp/event.json || { echo "BASE64 DECODE FAILED"; exit 12; }
            echo "[4] event.json head:"
            head -c 200 /tmp/event.json || true
            echo

            echo "[5] validate event json"
            jq -e . >/dev/null < /tmp/event.json || { echo "EVENT JSON INVALID"; exit 13; }

            echo "[6] extract bucket/key"
            jq -r '.notification[0].s3.bucket.name // empty' /tmp/event.json > /tmp/bucket.txt
            jq -r '.notification[0].s3.object.key // empty' /tmp/event.json > /tmp/key.txt

            echo "[6] bucket=$(cat /tmp/bucket.txt)"
            echo "[6] key=$(cat /tmp/key.txt)"

            # Make sure files exist even if empty (so outputs don’t crash)
            test -f /tmp/bucket.txt || echo -n "" > /tmp/bucket.txt
            test -f /tmp/key.txt || echo -n "" > /tmp/key.txt

    - name: echo
      inputs:
        parameters:
          - name: bucket
          - name: key
      container:
        image: alpine:3.20
        command: [sh, -lc]
        args:
          - |
            echo "bucket={{inputs.parameters.bucket}}"
            echo "key={{inputs.parameters.key}}"
