apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: install-avp
          image: ghcr.io/argoproj-labs/argocd-vault-plugin:v1.18.0
          command: ["sh", "-c"]
          args:
            - cp /usr/local/bin/argocd-vault-plugin /custom-tools/argocd-vault-plugin
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: repo-server
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin
      volumes:
        - name: custom-tools
          emptyDir: {}
