apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-submitter
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-submit
  namespace: argo-workflows
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtemplates"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-submit-from-argo-events
  namespace: argo-workflows
subjects:
- kind: ServiceAccount
  name: argo-events-submitter
  namespace: argo-events
roleRef:
  kind: Role
  name: workflow-submit
  apiGroup: rbac.authorization.k8s.io
