apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-read-data-storage
  namespace: python-ide
spec:
  provider:
    kubernetes:
      remoteNamespace: data-storage
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tIE1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkgZG1WeUxXTmhRREUzTmpJek5qWTNOamt3SGhjTk1qVXhNVEExTVRneE9USTVXaGNOTXpVeE1UQXpNVGd4T1RJNSBXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpJek5qWTNOamt3V1RBVEJnY3Foa2pPIFBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTVCtMQm93ZWlGb0NUWW8rNEtBNzVWc1FqeUdVUXNMcVY0YkRLK2J5djEgdERMa1dvZ1hNMWcxWitCSVZaR24wMS9kSDl5c2lhcFpLYU1wYkpONHZWWklvMEl3UURBT0JnTlZIUThCQWY4RSBCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVStvMUFpRDhvQXVBSjluemU1eEEzIDUxWUhsQ3d3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnT1BqcDgrSnB3R1R0Zm02dDQxKzJLV0RsYTdLQUc3cGYgTitFd1hWeWE0NjBDSVFET2pYd3FSdmhpN0J4VTNmQUFHa3VTc0N2REtBcmVZcGZaSXNleUJBRGNoZz09IC0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
      auth:
        serviceAccount:
          name: sa-read-data-storage
